### PR TITLE
Add hash-based routing support

### PR DESCRIPTION
**Pull request by RokLenarcic**
Adds hash based routing support to html5history

### CODE REVIEW

**Comment by awkay** [comment]
Thanks for working on this. You cannot change the signature or otherwise delete a non-private function in a namespace. That is a breaking change. The existing functions need to remain, and continue working as they did before. You can reimplement it in terms of your new function, but you cannot remove it or change signature.

**Comment by RokLenarcic** [comment]
@awkay Is the modified PR OK or not?

**Comment by awkay** [comment]
The code looks fine. Nice cleanup work. Have you tested it heavily? Did you use the current demo and make sure things like:

* Reloading with query parameters on a route restores the page to the correct state (e.g. a report on a given page with a selected row should re-show with that exact configuration).  Basically, that query parameters are not affected.
* Did you try your hash-based setting with the demo as well?

Since RAD runs real code in production (for me and others) I am *not* quick to merge something that touches critical path code without the author saying something about the risk mitigation that has been done. Basically, if you don't convince me that it is very well tested, then *I* have to test it, and am not willing to merge it until I have time to do so.

**Comment by RokLenarcic** [comment]
I have plugged it into the fulcro-rad-demo and tested it by clicking through the pages and reloading and both routers seem to function identically. Yes I have tested selecting a report row and reloading. I did use it myself for a small project but that's a very simple usecase. 

At worst the new routing doesn't work perfectly, I don't think there's a real danger for any existing code that uses the regular path based routing, because that code is the same, only some parts got factored out.

**Comment by awkay** [comment]
Thanks, I appreciate you checking!

**Comment by awkay** [comment]
Released in RC14

**Pull request merged**
