### PR TITLE
Fix Clojure 1.11 compilation warnings (exclude parse-long)

### PR DESCRIPTION
**Pull request by danskarda**

### CODE REVIEW

**Comment by awkay** [comment]
Do these cause problems if you use older Clojure, since those symbols aren't there?

**Comment by danskarda** [comment]
Good question. It should not. You can try `(:refer-clojure :exclude [this-symbol-does-not-exists])`. It compiles without any problem.

You can check implementation of `clojure.core/refer` which transforms `:exclude` into a set and then uses the set to filter out unwanted symbols.

**Comment by awkay** [comment]
Great, thanks for checking :)

**Comment by awkay** [comment]
Released

**Pull request merged**
